WordParser/WordParser/WordParser/Models/ParsedWordsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WordParser.Models
{
    public class ParsedWordsViewModel
    {
        public List<WordViewModel> Words { get; set; }
    }
}

WordParser/WordParser/WordParser/Models/WordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WordParser.Models
{
    public class WordViewModel
    {
        public string  Word { get; set; }
    
        public int Count { get; set; }
        
    }
}

WordParser/WordParser/WordParser/Controllers/ParseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WordParser.Models;
using WordParser.Service;
using WordParser.Domain;

namespace WordParser.Controllers
{
    public class ParseController : Controller
    {
        private IParserService _parserService;

        public ParseController(IParserService parserService)
        {
            _parserService = parserService;
        }

        //
        // GET: /Parse/

        public ActionResult Index()
        {
            return View(new ParsedWordsViewModel()
                {
                    Words = new List<WordViewModel>()
                });
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            var result = new ParsedWordsViewModel
            {
                Words = new List<WordViewModel>()
            };
 
            if (file != null && file.ContentLength > 0)
            {
                const string supportedType = "txt";
                var fileExt = System.IO.Path.GetExtension(file.FileName).Substring(1);

                if (fileExt != supportedType)
                {
                    ModelState.AddModelError("file", "File not supported. Only .txt files are valid.");
                    return View(result);
                }

                var parsedWords = _parserService.Parse(file.InputStream);

                foreach (var current in parsedWords)
                {
                    var converted = current.ToViewModel();
                    result.Words.Add(converted);
                }
                return View(result);
            }
            else
            {
                return View(result);
            }
        }

    }
}

WordParser/WordParser/WordParser/Views/Parse/Index.cshtml
@using WordParser.Models
@model WordParser.Models.ParsedWordsViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    $(function () {
        
        // hide the results table when a new file has been selected.
        $('#file').click(function() {
            $('#results').hide();
        });
    });
    
</script>

@using (Html.BeginForm("Index", "Parse", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container-fluid">
        <div class="row-fluid">
            <fieldset>
                <legend>Word Parser</legend>
                
                <div class="text-error">
                    @Html.ValidationMessage("file")
                </div>

                <label>Select a file for parsing.</label>
                <input type="file" name="file" id="file"/>
                
                <input type="submit" value="Parse" class="btn"/>
            </fieldset>
        </div>
        <br/>
        @if (Model.Words.Count > 0)
        {
            <div class="row-fluid" id="results">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Word</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var currentWord in Model.Words)
                        {
                            <tr>
                                <td>@Html.Label(currentWord.Word) </td>
                                <td>@Html.Label(currentWord.Count.ToString()) </td>
                            </tr>    
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
}

WordParser/WordParser/WordParser/Views/Parse/IndexAjax.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*
    THIS IS NOT COMPLETE, AS IT IS NOT POSSIBLE TO TRANSFER FILE VIA AJAX.
    http://stackoverflow.com/questions/12928186/ajax-form-post-not-posting-input-type-with-file?lq=1
*@

<script type="text/javascript">
    var WordViewModel = function(word, count) {
        var self = this;

        self.Word = ko.observable(word);
        self.Count = ko.observable(count);
    };

    var ParsedWordsViewModel = function() {

        var self = this;
        
        self.Words = ko.observableArray();

        self.ShowResults = ko.computed(function() {
            if (self.Words().count > 0) {
                return true;
            } else {
                return false;
            }
        });

        self.UpdateResult = function(result) {
            self = this;

            self.Words.removeAll();
            
            for (var index = 0; index < result.length; index++) {
                
                var newWord = new WordViewModel(result[index].Word,
                    result[index].count);

                self.Words.push(newWord);
            }
        };

        self.ParseTextFile = function() {
            alert('ParseTextFile fired.');
            
            var data = {
                filePath: $("#file").val(),
            };
            
            $.ajax({
                type: 'POST',
                url: '/Parse/Index',
                contentType: 'multipart/form-data; charset=utf-8',
                data: $("#file").val(),
                dataType: 'json',
                error: function (XMLHttpRequest, textStatus, errorThrown) {

                    var msg = JSON.parse(XMLHttpRequest.responseText);
                    self.ErrorMessage(msg.Message);
                },
                success: function (response) {

                    //alert("success from server");
                    self.ActionTriggered(true);
                    UpdateResult(response);
                }
            });

        };
    };
    
</script>

<script type="text/javascript">
    
    // apply bindings 
    $(function () {
        vm = new ParsedWordsViewModel();
        ko.applyBindings(vm);
    });
    
</script>

<div id="ParseView">
    <div class="container-fluid">
        <h2>Word Parser</h2>

        <div class="row-fluid">
            <p>
                Select a file for parsing.
            </p>

            <input type="file" name="file" id="file" class="btn-small"/>
            <input type="submit" value="Parse" class="btn-small" data-bind="click: ParseTextFile"/>
        </div>
        <div class="row-fluid" id="results">
            <!-- ko if: ShowResults   -->
            <table class="table-striped table-bordered" data-bind="with: Words">
                <thead>
                    <tr>
                        <th>Word</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td data-bind="text: Word"></td>
                        <td data-bind="text: Count"></td>
                    </tr>
                </tbody>
            </table>
            <!-- /ko -->
            
        </div>
    </div>
</div>

WordParser/WordParser/WordParser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrapcss")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    
    @RenderSection("scripts", required: false)
</body>
</html>